# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

fpath=(/usr/local/share/zsh-completions $fpath)

##################
# Custom Aliases #
##################

alias bez="bundle exec zeus"
alias berc="bundle exec rails console"
alias bers="bundle exec rails server"
alias berm="bundle exec rake db:migrate"

alias https="ruby -run -e /httpd . -p 8080"

alias ne='PATH=$(npm bin):$PATH'

alias gbc="git branch --no-color --merged master | grep -v master | xargs git branch -d"
alias ggc="gl && gfa && gbc"
alias gll="gl --no-ff origin"

alias weather="curl -4 http://wttr.in/"

alias deploy="~/dev/code/helm-deployment-charts/deploy.sh"
alias change_cluster="~/dev/code/helm-deployment-charts/change_cluster.sh"

alias up="cd ~/dev/docker && docker-compose up -d && itermocil gat_app"

alias dc="docker-compose"

#Searchspring aliases
alias jenkins-e="ssh -t lostrowski@54.175.178.84 -A -N -L 8085:localhost:8080"
alias jenkins-w="ssh -t lostrowski@54.183.184.33 -A -N -L 8086:localhost:8080"

########################################
# Directories to be prepended to $PATH #
########################################

export ANDROID_HOME=$HOME/Library/Android/sdk

declare -a dirs_to_prepend
dirs_to_prepend=(
  "~/Library/Python/3.7/bin"
  "/usr/local/opt/imagemagick@6/bin"
  "/usr/local/opt/openssl/bin"
  "/usr/local/opt/postgresql@9.6/bin"
  "/usr/local/sbin"
  "/usr/local"
  "$HOME/.rbenv/bin"
  "$HOME/bin"
  "$HOME/.yarn/bin"
  "$HOME/.config/yarn/global/node_modules/.bin"
)

# Explicitly configured $PATH
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend

export PATH

########################################
# Theme and plugins #
########################################

ZSH_THEME="aussiegeek"

COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which   would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse kubectl)
# Add wisely, as too many plugins slow down shell startup.

plugins=(git rails bundler z brew history osx zsh-autosuggestions zsh-syntax-highlighting)

######################
# User configuration #
######################

# Load the shell dotfiles
for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
if [[ "$OSTYPE" == "darwin"* ]]; then
  if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
  fi
fi

source $ZSH/oh-my-zsh.sh

#ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[cursor]='bold'

ZSH_HIGHLIGHT_STYLES[alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=green,bold'
ZSH_HIGHLIGHT_MAXLENGTH=300

# Source local extra (private) settings specific to machine if it exists
[ -f ~/.zsh.local ] && source ~/.zsh.local

export DEPS_AWS_CONFIG_PATH="~/.aws/config"
export DEPS_AWS_PROFILE="default"

eval "$(rbenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '~/code/google-cloud-sdk/path.zsh.inc' ]; then . '~/code/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '~/code/google-cloud-sdk/completion.zsh.inc' ]; then . '~/code/google-cloud-sdk/completion.zsh.inc'; fi
