# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

fpath=(/usr/local/share/zsh-completions $fpath)

##################
# Custom Aliases #
##################

alias be="bundle exec"
alias bez="bundle exec zeus"
alias berc="bundle exec rails console"
alias bers="bundle exec rails server"
alias berm="bundle exec rake db:migrate"

alias https="ruby -run -e /httpd . -p 8080"

alias ne='PATH=$(npm bin):$PATH'

alias gbc="git branch --no-color --merged master | grep -v master | xargs git branch -d"
alias ggc="gl && gfa && gbc"

alias weather="curl -4 http://wttr.in/"

alias list-tags="gcloud beta container images list-tags eu.gcr.io/dulcet-provider-591/deployment-gat-app-image"
alias deploy="/Users/lukasz/dev/code/helm-deployment-charts/deploy.sh"

########################################
# Directories to be prepended to $PATH #
########################################

declare -a dirs_to_prepend
dirs_to_prepend=(
  "/usr/local/sbin"
  # "/usr/local/git/bin"
  "/usr/local"
  "$HOME/.rbenv/bin"
  "$HOME/bin"
  # "/usr/local/mysql/bin"
  # "/opt/local/bin"
  # "/opt/local/sbin"
  # "$HOME/dotfiles/bin"
  # "$HOME/bin"
  # "$HOME/.yarn/bin"
  # "$HOME/.npm-global/bin"
  # "$(brew --prefix ruby)/bin"
  # "$(brew --prefix coreutils)/libexec/gnubin" # Add brew-installed GNU core utilities bin
  # "$(brew --prefix)/share/npm/bin" # Add npm-installed package bin
)

# Explicitly configured $PATH
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend

export PATH


# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Z beats cd most of the time
# . ~/z/z.sh

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which   would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git rails ruby z brew node npm history zsh-syntax-highlighting osx)

######################
# User configuration #
######################

# Load the shell dotfiles
for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

source $ZSH/oh-my-zsh.sh

# Source local extra (private) settings specific to machine if it exists
[ -f ~/.zsh.local ] && source ~/.zsh.local

# npm tab completion
. <(npm completion)


export DEPS_AWS_CONFIG_PATH="/Users/lukasz/.aws/config"
export DEPS_AWS_PROFILE="default"

export NVM_DIR="/Users/lukasz/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/lukasz/lib/bin/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/lukasz/lib/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/lukasz/lib/bin/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/lukasz/lib/bin/google-cloud-sdk/completion.zsh.inc'; fi



  eval "$(rbenv init -)"
eval "$(thefuck --alias)"
