# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

fpath=(/usr/local/share/zsh-completions $fpath)

##################
# Custom Aliases #
##################

alias bez="bundle exec zeus"
alias berc="bundle exec rails console"
alias bers="bundle exec rails server"
alias berm="bundle exec rake db:migrate"

alias https="ruby -run -e /httpd . -p 8080"

alias ne='PATH=$(npm bin):$PATH'

alias gbc="git branch --no-color --merged master | grep -v master | xargs git branch -d"
alias gbcs='git checkout -q master && git for-each-ref refs/heads/ "--format=%(refname:short)" | while read branch; do mergeBase=$(git merge-base master $branch) && [[ $(git cherry master $(git commit-tree $(git rev-parse $branch\^{tree}) -p $mergeBase -m _)) == "-"* ]] && git branch -D $branch; done'
alias ggc="gl && gfa && gbc && gbcs"
alias gll="gl --no-ff origin"

alias weather="curl -4 http://wttr.in/"

alias deploy="~/dev/code/helm-deployment-charts/deploy.sh"
alias change_cluster="~/dev/code/helm-deployment-charts/change_cluster.sh"

alias up="cd ~/dev/docker && docker-compose up -d && itermocil gat_app"

alias dc="docker-compose"

#Searchspring aliases
alias jenkins-e="ssh -t lostrowski@54.175.178.84 -A -N -L 8085:localhost:8080"
alias jenkins-w="ssh -t lostrowski@54.183.184.33 -A -N -L 8086:localhost:8080"

alias keast2='kubectl --context=e --user=lukasz.ostrowski@searchspring.com'
alias kwest2='kubectl --context=w --user=lukasz.ostrowski@searchspring.com'

alias kdacq='kubectl -n dacq-streaming'
alias hdacq='helm -n dacq-streaming'
alias w2='watch -n2'

########################################
# Directories to be prepended to $PATH #
########################################

export ANDROID_HOME=$HOME/Library/Android/sdk
export GOPATH=/usr/local/go

declare -a dirs_to_prepend
dirs_to_prepend=(
  "~/Library/Python/3.7/bin"
  "/usr/local/opt/imagemagick@6/bin"
  "/usr/local/opt/openssl/bin"
  "/usr/local/opt/postgresql@9.6/bin"
  "/usr/local/sbin"
  "/usr/local"
  "$HOME/.rbenv/bin"
  "$HOME/bin"
  "$GOPATH/bin"
  "$HOME/go/bin"
)

# Explicitly configured $PATH
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

for dir in ${(k)dirs_to_prepend[@]}
do
  if [ -d ${dir} ]; then
    # If these directories exist, then prepend them to existing PATH
    PATH="${dir}:$PATH"
  fi
done

unset dirs_to_prepend

export PATH
export JAVA_HOME_8=$(/usr/libexec/java_home -v1.8)
export JAVA_HOME_14=$(/usr/libexec/java_home -v14)

export JAVA_HOME=$JAVA_HOME_8


########################################
# Scripts #
########################################

# Automatically list directory contents on `cd`.
auto-ls () {
	emulate -L zsh;
	# explicit sexy ls'ing as aliases arent honored in here.
	hash gls >/dev/null 2>&1 && CLICOLOR_FORCE=1 gls -aFh --color --group-directories-first || ls
}
chpwd_functions=( auto-ls $chpwd_functions )

########################################
# Theme and plugins #
########################################

ZSH_THEME="aussiegeek"

COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which   would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse kubectl)
# Add wisely, as too many plugins slow down shell startup.

plugins=(git rails bundler z brew history osx zsh-autosuggestions zsh-syntax-highlighting kubectl dotenv helm)

######################
# User configuration #
######################

# Load the shell dotfiles
for file in $HOME/.{shell_exports,shell_aliases,shell_functions,shell_config}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
if [[ "$OSTYPE" == "darwin"* ]]; then
  if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
  fi
fi

source $ZSH/oh-my-zsh.sh

#ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)
ZSH_HIGHLIGHT_STYLES[cursor]='bold'

ZSH_HIGHLIGHT_STYLES[alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[function]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=green,bold'
ZSH_HIGHLIGHT_MAXLENGTH=300

# Source local extra (private) settings specific to machine if it exists
[ -f ~/.zsh.local ] && source ~/.zsh.local

export DEPS_AWS_CONFIG_PATH="~/.aws/config"
export DEPS_AWS_PROFILE="default"

export SS_ANALYTICS_TUNNEL_USERNAME=lostrowski
export SS_TUNNEL_USERNAME=lostrowski
export SS_ANALYTICS_TUNNEL_KEY_FILENAME=id_rsa

eval "$(rbenv init -)"


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/lukasz/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/lukasz/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/lukasz/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/lukasz/google-cloud-sdk/completion.zsh.inc'; fi
export PATH="/usr/local/opt/node@14/bin:$PATH"
