#!/bin/bash

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! hash brew 2/dev/null; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle
  fi

fi

if [ "$system_type" = "Linux" ]; then
  sudo ~/.config/yadm/apt.sh

  if ! hash starship 2>/dev/null; then
    sh <(curl -sS https://starship.rs/install.sh) -y
  fi

  chsh -s $(which zsh)

  if hash lsd 2>/dev/null; then
    # install lsd
    SYSTEM_DEB_SUFFIX=$(dpkg --print-architecture)
    TEMP_DEB="$(mktemp)" &&
      echo https://github.com/Peltoche/lsd/releases/download/0.23.1/lsd_0.23.1_$SYSTEM_DEB_SUFFIX.deb |
      wget --show-progress -O "$TEMP_DEB" -qNi - &&
      sudo dpkg --skip-same-version -i "$TEMP_DEB"
      rm -f "$TEMP_DEB"
  fi
fi

if [ ! -d ~/.zinit ]; then
  mkdir ~/.zinit
  chmod go-w ~/.zinit # to avoid insecure directories complaint
  git clone https://github.com/zdharma-continuum/zinit.git ~/.zinit/bin
fi

###############################################################################
# custom
###############################################################################

if hash python 2>/dev/null; then
  sudo ln -s $(which python3) /usr/local/bin/python
fi