version: "2"

services:

  # prometheus:
  #   network_mode: "host"
  #   mem_limit: 256mb
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - "9090"
  #   expose:
  #     - 9090
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/:z
  #     - prometheus_data:/prometheus:z
  #   command:
  #     - '-config.file=/etc/prometheus/prometheus.yml'
  #     - '-storage.local.path=/prometheus'

  grafana:
    mem_limit: 256mb
    image: grafana/grafana
    ports:
      - "9091:3000"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana

  redis:
    mem_limit: 256mb
    memswap_limit: 0mb
    image: redis
    ports:
      - "6379:6379"

  elasticsearch:
    mem_limit: 256mb
    memswap_limit: 0mb
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    tty: true
    environment:
      - MAX_LOCKED_MEMORY=100000
      - MAX_OPEN_FILES=65535
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    volumes:
      - ./elastic/:/usr/share/elasticsearch/config/:z

  mysql:
    mem_limit: 256mb
    memswap_limit: 0mb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - ./database/mysql:/var/lib/mysql

volumes:
    prometheus_data: {}
    grafana_data: {}

